// src/components/vue/RatioArea.tsx
import { ReactNode } from "react"
import { twMerge } from 'tailwind-merge'
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    className: {
      type: String,
      default: '',
    },
    ratio: {
      type: [Number, String],
      required: true,
    }
  },
  setup(props, {emit, slots}){
    return ()=> <div className={twMerge('ratioArea relative w-full', props?.className)}>
    <div className="fill pointer-events-none relative"
    style={{
      width: '100%',
      paddingBottom: `${props.ratio}%`
    }}></div>
    { (slots?.default?.() as ReactNode) }
  </div>
  }
})

// src/components/react/RatioArea.tsx
import { twMerge } from 'tailwind-merge'

interface TypeProps {
  ratio: number | string
  children: React.ReactNode
  className?: string
}

export default function RatioArea(props:TypeProps){
  return (
    <div className={twMerge('ratioArea relative w-full', props?.className)}>
      <div className="fill pointer-events-none relative"
      style={{
        width: '100%',
        paddingBottom: `${props.ratio}%`
      }}></div>
      { props.children }
    </div>
  )
}
