// src/components/vue/RatioArea.vue
<script setup lang="ts">
import { computed } from 'vue'
import { twMerge } from 'tailwind-merge'

interface Props {
  className?: string
  class?: string
  ratio: number | string
}

const props = defineProps<Props>()

const mergedClassName = computed(() =>
  twMerge('ratioArea relative w-full', props.class || props.className)
)

const paddingStyle = computed(() => ({
  width: '100%',
  paddingBottom: `${props.ratio}%`
}))
</script>

<template>
  <div :class="mergedClassName">
    <div
    class="fill pointer-events-none relative"
    :style="paddingStyle" />
    <slot />
  </div>
</template>

// src/components/react/RatioArea.tsx
import { twMerge } from 'tailwind-merge'

interface TypeProps {
  ratio: number | string
  children: React.ReactNode
  className?: string
}

export default function RatioArea(props:TypeProps){
  return (
    <div className={twMerge('ratioArea relative w-full', props?.className)}>
      <div className="fill pointer-events-none relative"
      style={{
        width: '100%',
        paddingBottom: `${props.ratio}%`
      }}></div>
      { props.children }
    </div>
  )
}
